source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MyLabel_Example', :exclusive => true do
  pod "MyLabel", :path => "../"
end

target 'MyLabel_Tests', :exclusive => true do
  pod "MyLabel", :path => "../"

  
end
